### ISSUE TITLE
Which characters should be included and how to type them?

### ISSUE THREAD

**Issue by ArenaL5** [Julow/Unexpected-Keyboard#108]
**Summary: This is not actually an issue but a discussion about: 1) which characters should be included, 2) where and 3) guidelines for key combinationts to use (like Fn+hyphen for N dash)**

One of the things I like about this keyboard is being able to just having any sometimes-used character with just a swipe. There are a couple of oddities to this, mostly regarding quotation marks and extra layouts.

There are some characters, mostly quotation marks, which can be accessed using weird, non-intuitive combinations:

https://github.com/Julow/Unexpected-Keyboard/blob/ba6d62dee2a1c0dae63eb758551b089a7cd9ffc1/srcs/juloo.keyboard2/KeyModifier.java#L71-L104

Is there a pattern to them? If not, should I make them fit a pattern? My proposal would be to change most of these combos to ones with Fn, Shift, and Fn+Shift.

I can also see that some characters, especially dead accents, move a lot from layout to layout. Some amount of this is to be expected as they accommodate characters for a particular language, but do you have any guidelines in order to make the layouts more similar? (Anything like “down-left swipes are reserved for language-specific accented letters” or the like).

For my last question, do you have any scope for which characters should (or should never) be in the [qwerty.xml](https://github.com/Julow/Unexpected-Keyboard/blob/ba6d62dee2a1c0dae63eb758551b089a7cd9ffc1/res/xml/qwerty.xml) layout? While the languages I speak are fully covered, I would like to add diacritics for European languages. However, that might be a bit too much so I'd rather ask first. :sweat_smile:

Sorry for the long post!

**Comment by Julow** [comment]
These are interesting questions!
The weird combinations with the accent keys are not really well thought. The reasons for the cases `FLAG_ACCENT4` and `FLAG_ACCENT5` are to add characters from the Spanish and French keyboards. No particular reasons for `FLAG_ACCENT2`.
In hindsight, this wasn't a good idea. These combinations are not obvious and probably hard to remember if we add more.
`Fn` is the right modifier I think but it has already a lot of combinations. `Fn+Shift` is too many steps. `Alt` might be used too but there's a limitation, `Alt`, `Ctrl`, `Meta` and `Shift` can't modify keys that have an associated "key event" (see https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/KeyValue.java#L174) because that would interfere with the primary goal of the keyboard.
There's also "localized" keys, like `ß`, configured in https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/method.xml

Dead-keys don't have a dedicated place on layouts but this is a good idea!

There's a distinction between "programming" and "localized" layouts. I want every programming layouts to be able to type latin-script languages, hence the dead-keys and the weird combinations.

There's even less defined rules for localized layouts. The Latvian layout shows every accented letters but the Portuguese layout prefers dead-keys (except for ç). This should probably be written in the files as comments but I'm not against some consistency either.

**Comment by ArenaL5** [comment]
I'm glad you found them interesting! I was afraid of being a bit pushy with this. I'm still a bit nervous, actually.

I wasn't really aware of the distinction between programming and localized layouts. Focusing only on the programming layout for the moment, I believe we can fit pretty much every Latin letter with the current estate and use of the Fn key, without ever involving the Alt key (as pretty much every single symbol generates a key event), with some minimal rearrangement.

Regarding the quotation marks... there is a _lot_ of variety in European languages. It wouldn't be practical to include [every single non-ASCII character](https://en.wikipedia.org/wiki/Quotation_mark#Unicode_code_point_table), but this looks like a good sample for every language:

`« » ‹ › ‘ ’ “ ” ‚ „`

Maybe those could be paired with brackets and ASCII quotation marks?:

```
without Fn key: < > { } [ ] ( ) ' "
with    Fn key: « » ‹ › ‘ ’ “ ” ‚ „`
```

This would mean that the arrows `←→⇐⇒` would have to go, but those can be set to 4, 6, Fn+4 and Fn+6 on the numeric keyboard. You could even add more arrows in other number keys.

The Fn key could also be used to generate:

```
. → …
, → ·
! → ¡
? → ¿
space → non breaking space
```

Maybe combinations like Fn+O could be used in order to generate extended Latin letters, like Œ? Or would you see that as too much?

**Comment by Julow** [comment]
I really like the idea of quotation marks on brackets ! Would you be interested in making the changes ?

Arrows on number wouldn't work at the moment because Fn+number are the function keys. This is not ideal because F11 and F12 are awkwardly placed and the number pad don't need them, I'd like to improve that but not now.
Perhaps these arrow symbols can just be placed on the number pad and not under Fn ?

Yes …, ·, ¡, ¿, æ, œ are all useful. I like the non breaking space but we need a symbol (perhaps "nbsp" literally, I have no idea how the glyph could look like).

**Comment by ArenaL5** [comment]
Absolutely. I can start this weekend making some changes. I'm also going to fix an oversight on the Spanish keyboard in the same pull request, by the way: `·` should be added to the Ñ key on the Spanish keyboard. (It is used on Catalan, and is included in any Spain layout).

Yes, I meant putting the arrows directly on the numpad. Swipe on a digit for a thin arrow, Fn + swipe for a double-lined arrow. Sorry if that wasn't clear.

I hadn't really thought about the symbol and was fully expecting to use `NBSP`, but then I checked [the table where ␣ is listed](https://en.wikipedia.org/wiki/Whitespace_character#Substitute_images). Apparently the symbol is `⍽` U+237D Shouldered open box (it's supposed to be ␣ but with two extra strokes). Which would you prefer or find clearer?

About more useful symbols and diacritics... I've done some research a while back in order to suggest to the [EurKEY](https://eurkey.steffen.bruentjen.eu/) designers to be able to type pretty much any European name (note I don't actually speak any of the following languages). Adding all of these diacritics directly to the programming layout makes it pretty busy, but using Fn to choose different diacritics sounds like too many steps. What do you think?

- Dot above (for Polish and Turkish)
- Double acute (for Hungarian)
- Ogonek (like a cedilla but curving the other side) (for Lithuanian)
- Breve (for Romanian, Esperanto and Turkish)
- Comma below (for Romanian)

Not mentioning the use of Ł,  Ð and Ŋ (Polish, Icelandic, and several Sami languages) because that can be handily be taken of using Fn + letter.

The last point I can think of (for now) is currency symbols, like they are asking for at #90. Should they be added to the numpad like @ChiefMikeK suggests? Maybe a currency flag/accent/key is in order, to type e.g. ¤+E for `€`?

**Comment by sdrapha** [comment]
I had an idea to try to create a input in the settings, for a custom Currency symbol, since there are so many. This way we keep the layouts more maintainable in the long run, without clutter. 
I didn't explore this idea yet thou, so I don't know if its feasible. (personaly I only need $, so I'm all set) 
Just giving an idea, if it helps anything.

**Comment by sdrapha** [comment]
Another idea, if there is appetite for a whole bunch of currency symbols, could be the addition of a new modifier, like the Sup, Sub or Ord, a new one dedicated to Currency, there could be a whole alphabet of currency symbols in place of the regular keys

**Comment by ArenaL5** [comment]
> Another idea, if there is appetite for a whole bunch of currency symbols, could be the addition of a new modifier, like the Sup, Sub or Ord, a new one dedicated to Currency, there could be a whole alphabet of currency symbols in place of the regular keys

Exactly, that's what I meant! Your explanation is much clearer.

> I had an idea to try to create an input in the settings, for a custom Currency symbol, since there are so many. This way we keep the layouts more maintainable in the long run, without clutter.
I didn't explore this idea yet thou, so I don't know if its feasible. (personaly I only need $, so I'm all set)
Just giving an idea, if it helps anything.

That could be an option too... However, the US dollar `$` should always be on the keyboard. The `$` sign is a basic ASCII sign, and used in several programming and scripting languages, and this keyboard is meant for programmers after all.

So keyboards could have two currency signs. `$`, and then a second sign for `€` or `¢` or whichever.

I personally find the Currency modifier easier and nicer for everybody. It should probably also act on Cyrillic letters, too, e.g. Currency `¤` + Cyrillic Es `С` = Cent symbol `¢`.

**Comment by Julow** [comment]
The "shouldered open box" symbol works for me.

EurKEY is very interesting, thanks for the discovery. Adding all the languages at once isn't a goal, I don't want to pretend the keyboard supports all the latin script languages while it hasn't been reviewed carefully. EurKEY seems to be well made but I'd prefer to add languages one by one while users are giving feedback.
I don't want to cram Fn, I'd prefer to add dead-keys dedicated to every diacritics and keeping Fn for characters other than letters. But I'm also thinking about ways of putting locale-specific characters on the main keyboard without making layouts too complicated.

I planned on adding some currency symbols for the next release, they will be placed on the keyboard but hidden when the users don't have a corresponding language installed. I plan on trying an other approach in the future that doesn't involve allocating a spot on every layouts for every currencies (perhaps reserving a specific corner on a specific row or something else, same for ß).

I'd like to avoid showing every currency symbols on the keyboard. Most people need one or two of them and I have an other plan that can take care of this in a more general way. I plan on adding [xkb's compose key](https://en.wikipedia.org/wiki/Compose_key) sequences to the keyboard somehow, perhaps when/if I implement word suggestions or perhaps with an actual compose key.

Thanks for the ideas!

**Comment by Dakkaron** [comment]
I speak German an English.The only symbol I am missing so far is °, which is used to denote degrees (as in an angle of 90° or a temperature of 20°C).

**Comment by sdrapha** [comment]
> I speak German an English.The only symbol I am missing so far is °, which is used to denote degrees (as in an angle of 90° or a temperature of 20°C).

It's already there, `Fn + *` at least on the qwerty layout, I don't know about the german layout, but it's also on the numeric keyboard for all languages

**Comment by Dakkaron** [comment]
> > I speak German an English.The only symbol I am missing so far is °, which is used to denote degrees (as in an angle of 90° or a temperature of 20°C).
> 
> It's already there, `Fn + *` at least on the qwerty layout, I don't know about the german layout, but it's also on the numeric keyboard for all languages

Nice, thanks! I couldn't find it. It is on both locations in the German layout.

**Comment by HARDY8118** [comment]
Was wondering if a ₹ (unicode: U+20B9) could be added. I have to switch keyboards just for this symbol.

**Comment by Julow** [comment]
The keyboard evolved a bit since this issue was opened. The `Fn` layer contains many more symbols and it's now easier to add both new layouts and new dead-keys. (and many were added)
It's also possible to add extra symbols to layout depending on the enabled languages, without affecting the definition of the layouts. (2e81cb5)

@HARDY8118 Sorry for the slow reply, ₹ is `Fn+r` since 5f47beb.

I'm closing this because most of the suggestion are implemented, please open new issues for more suggestions.
