### ISSUE TITLE
Issues with display scaling

### ISSUE THREAD

**Issue by Dakkaron** [Julow/Unexpected-Keyboard#113]
I just discovered this keyboard, and it is pretty amazing! I currently use Gboard for typing regular text and the Hacker's Keyboard for the shell. I might be able to replace both with this keyboard.

I just have one major issue with this keyboard, and that has to do with display scaling.

To fit more stuff on the screen, I set the "Smallest Width" value in the developer settings to 597 (the highest value where Android doesn't activate tablet UI).

Aparently, this keyboard uses the distance in dp to determine the length of of a gesture instead of the distance in milimeters. That means, the app thinks, I am moving my fingers much farther than I actually do. Even if I set the gesture length to the maximum, I still frequently get accidental special characters, and the cursor key button is basically unusable, because it is extremely fast.

Regarding that, it might also be nice, to have a slider that allows for adjusting the total cursor speed. So, that slider would just be a multiplier for the distance of the cursor gesture.

**Comment by Julow** [comment]
Thanks for the report! This should be fixed in the next release. (2b6c2b9)

Your analyse was right but I decided not to use an absolute measurement (millimeters) but one relative to the screen (the size of the screen in pixels and the dpi of the actual screen). The value should not be affected by the accessibility options.

The arrow key speed isn't ideal at the moment and there are many ideas in the issues. I'd rather not add an option for now, as I'm considering entirely changing how they work.

**Comment by Dakkaron** [comment]
Nice! Thanks for the quick fix! I'll report once I have the new build on my phone!

Regarding the arrow keys: The same issue also exists for all key repeats, though it's not that important there, because it isn't used that much. But the key repeat speed is really fast.
