### ISSUE TITLE
Shift key remains on for two characters

### ISSUE THREAD

**Issue by tonyaajjackson** [Julow/Unexpected-Keyboard#122]
Expected Behaviour:
When I press the shift key once to get a single uppercase character, then press two characters quickly in sequence, only the first character should be capitalized.

Example:
"Hello"

Actual Behaviour:
When I press the shift key once to get a single uppercase character, then press two characters quickly in sequence, the first two characters are capitalized.

Example:
"HEllo"

Reproduction steps:
- Press shift key once
- Press first letter (e.g. "H") and don't let go
- Press second letter (e.g. "E"), then let both go

If you do this quickly enough to not trigger the character repeat, both characters will be capitalized.

Notes:
It seems like the shift key state is changing on the key-up, but should change on key-down. This may sound like a rare bug but it happens quite frequently to me when typing.

Version Info:
Unexpected Keyboard 1.14.1 installed via FDroid
OnePlus A6003
OxygenOS 11.1.2.2

P.S. This keyboard is fantastic - thank you for all your hard work in developing and maintaining it

**Comment by Julow** [comment]
Thanks for the report! You are right, the shift state should be cleared on key down (except for the currently pressed key, in case a character in the corners is affected by it).

**Comment by tonyaajjackson** [comment]
This bug is giving me grief and I really like the keyboard otherwise so I've spun up a bounty for fixing the issue:
https://app.bountysource.com/issues/107839514-shift-key-remains-on-for-two-characters

**Comment by Julow** [comment]
Sorry for the slow answer, I initially didn't plan on making a release this month. This should be fixed since b72635b, I'll release tomorrow to have time to be sure it is fixed and to fix a few other things.
If you wish to try the new version soon, you can find a debug version [here](https://github.com/Julow/Unexpected-Keyboard/actions/runs/2251293737), otherwise the release process should take several days (especially on F-Droid).

Thanks for the bounty!
