### ISSUE TITLE
Add the ß Symbol for the letter S on QWERTZ

### ISSUE THREAD

**Issue by ethernia-root** [Julow/Unexpected-Keyboard#140]
as a German, i need this.

**Comment by Julow** [comment]
`ß` should be on the keyboard, on a corner of the `s` key but you are not seeing because of a subtlety that I'm planning to fix.

Before that, there's two workarounds, do one of:
- Add the German language to your device. If it is already, there might be a bug easy to fix here.
- In the keyboard's settings, turn the "Accents" option to "Show every accents".

**Comment by ethernia-root** [comment]
I have both, It still doesn't show, but if its gonna be fixed soon, i can wait and just use "ss" instead!

**Comment by Julow** [comment]
In case my initial plan is re-scheduled, this should be fixed with eb42943.

Can I ask what language do you have enabled on your device ? (Which locale variant)

**Comment by ethernia-root** [comment]
i have english installed and german installed, but not enabled, even if german is enabled it doesnt show the ß.
ill try the updated version and test it out again
