### ISSUE TITLE
Diacritics missing on some keyboards

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#144]
Acute, grave, tilde, circumflex are missing for these keyboards: Portuguese, Spanish, Swedish,,

**Comment by sdrapha** [comment]
Do you use all these languages?
I'm curious to your anwser, because I know that portuguese is not missing those accents, they are achieved with the use of dead keys which are present, and portuguese speakers are used to that method.
The support for portuguese was added for pt-BR, do you speak any portuguese with a different region code? That maybe your issue maybe.

**Comment by Julow** [comment]
Thanks for checking the layouts and thanks @sdrapha for the answer. I'll close this issue until an affected user gives feedback, I'll keep https://github.com/Julow/Unexpected-Keyboard/issues/145 open to discuss inconsistencies in the layouts.

**Comment by GrimPixel** [comment]
@sdraphaI guess you are not a local. Look at this standard keyboard.
https://en.wikipedia.org/wiki/File:KB_Portuguese_Brazil.svg

I am not the speakers of these languages, so aren't you. You developed the keyboard, I point out what's wrong with them. They have nothing to do with whether any user get affected.

**Comment by GrimPixel** [comment]
I saw the xml. I just want to know who typed “accent_aigu”, “accent_circonflexe”.

**Comment by Julow** [comment]
You misunderstood the issue. What @sdrapha said is that the keyboard doesn't show the individual diacritics (á, é, í, ó, etc..) but show the dead keys instead. @sdrapha designed the layout and decided that dead keys are more suitable for his language.

The issue you hit is different. Since eb4294332 (not released yet), you will see the dead keys on the Brazilian layout. Layout != language.

I'm not entirely sure what the app you use is supposed to do to the keyboard but if you want to type in Brazilian, you need to enable the language in the device's settings.

**Comment by sdrapha** [comment]
I didn't designed the ptbr layout, I personaly like to use the original qwerty, which also have all the same dead keys accents needed for Portuguese.
And @Julow is right, please understand that layouts and languages are separate things, to show the accents you need the language in your device settings globally. Otherwise, I believe that if you turn on "Show ALL accents keys" on the keyboard settings also does the trick, if your language is not a supported one yet.
and man, calm down on pointing fingers, this is a community. not a paid service. feel free to contribute with a respectful and constructive approach

**Comment by GrimPixel** [comment]
My bad. There is an option I didn't notice.
Thank you for point that out. I didn't know it's so complicated.

**Comment by Julow** [comment]
> I didn't designed the ptbr layout

Sorry! It was added in https://github.com/Julow/Unexpected-keyboard/pull/91
