### ISSUE TITLE
letter indication for pin entry

### ISSUE THREAD

**Issue by kendfss** [Julow/Unexpected-Keyboard#153]
i think it would be good to display the letters associated with each key in the prompt used for pin code entry. they needn't be useful. i ask because th keypd layout is quite disorienting on those rare occasion it shows up.
it could also be worth adding the option to choose whether the numbers on the keypad increase as they go right/down instead of right/up.

**Comment by ChiefMikeK** [comment]
Are you asking for the alphabet like as telephone keys?  
![keypad](https://user-images.githubusercontent.com/20070053/169998510-255d206e-b992-47ab-acdb-eb52c03befac.png)

**Comment by kendfss** [comment]
precisely

**Comment by draxaris1010** [comment]
The keypad is more like a PC numpad.

**Comment by kendfss** [comment]
> The keypad is more like a PC numpad.

I figured, ime it only shows up when I need to enter a pin (though perhaps that says more of my particular use case for the keyboard). On a related note, there are other times i'd like to use it. Is there a way to select it manually? (sorry, very new to android)

for instance, here 
https://github.com/Julow/Unexpected-Keyboard/blob/master/metadata/android/en-US/images/phoneScreenshots/6.png
It could be placed in the bottom right of each number in white text.


That being said, another situation specific keyboard could be added/Perhaps this could be addressed by #31

**Comment by draxaris1010** [comment]
Yes, you can manually use it, just swipe right down from the Ctrl key.

**Comment by ChiefMikeK** [comment]
Even though I would prefer to keep things simple [not bloated] just creating a mockup for any discussion here.


![keyboard1](https://user-images.githubusercontent.com/20070053/170440443-960ea8b0-0cbe-452c-848c-cc28a4c5e486.png)

![4x4keypad](https://user-images.githubusercontent.com/20070053/170440572-be251039-0935-498f-9e46-ef267514f779.png)

**Comment by Julow** [comment]
Thanks for all the suggestions !

A layout dedicated for typing pins would be a good touch.

**Comment by sdrapha** [comment]
On my personal fork I added some logic to tie specific chars layouts to specific numerical layouts, so it's not just always the same in common for all.
Although that would be one easy way of adding an alternative numerical layout with reversed numbers, I don't believe that is the best way to acomplish this idea.

Another option would be to have the alternative numerical layout as an option on the settings, so the user can choose which order of numbers it likes more. and use that for all chars layouts.

Third option would be not an alternative numeric layout. but a totally new pane, and then adding one more key everywhere to access it without even changing anything on the existing numerical layout.
(for the third option, there would still be some conflict about which one would be the default to come up when clicking an number field, bringing back the second option into mind again, about having a setting)

What do you all think? I'm curious with the outcome either way.

ps. I think the third option adds more freedom to the pin layout, which is pretty cool. But it does have to be really well thought on where to put the switch key since there is going to be competition for the most priveleged spots on the bottom row. (should be a new separate extra key ? or should it be Fn+'123+' ?)

**Comment by draxaris1010** [comment]
For the third option the switch key layout key combination could be Fn+Tab or Fn+Backspace.

**Comment by Julow** [comment]
The pin entry layout with letter indications is added (e01a273, 2e598a4).
It shows up when typing phone numbers, dates and some numbers.

I used @ChiefMikeK's layouts with some keys added.

There's an issue open for configuring the layout: https://github.com/Julow/Unexpected-Keyboard/issues/178
