### ISSUE TITLE
Extra keys that are defined as localized in the keyboard layout are automatically placed in the second row

### ISSUE THREAD

**Issue by kidhanis** [Julow/Unexpected-Keyboard#161]
App version is 1.16.0 and on Android 11. I use English and Spanish on my phone, and on the app I set "Change keyboard layout" to "System settings" and  Accents to "Show accents for all installed languages".

## Observed behavior
When using the default QWERTY keyboard, all extra keys from Spanish are placed automatically on the second row, which is behavior added in commit 2e81cb5cf717ef68df9bd66d2af1c7f5ccaaa3fe.

## Expected behavior
The extra keys should be placed according to the qwerty.xml layout. For example, the tilde would be a swipe on the n key.  https://github.com/Julow/Unexpected-Keyboard/blob/402bf4990e33211ef47e794a095721080df18333/res/xml/qwerty.xml#L33
The commit message from 2e81cb5cf717ef68df9bd66d2af1c7f5ccaaa3fe seems to support this expected behavior.

<hr />

I haven't tested this, but I suspect that the extra keys are not being matched with the corresponding localized keys in the keyboard layout.  

Let's use tilde again as example.  In qwerty.xml, its name is `"loc accent_tilde"`, but in [method.xml](https://github.com/Julow/Unexpected-Keyboard/blob/402bf4990e33211ef47e794a095721080df18333/res/xml/method.xml) it's just `"accent_tilde"`.  Now see **KeyValue.getKeyByName**:
https://github.com/Julow/Unexpected-Keyboard/blob/402bf4990e33211ef47e794a095721080df18333/srcs/juloo.keyboard2/KeyValue.java#L211-L219
If `name` is `"accent_tilde"`, then line 213 returns the **KeyValue** object created in line 270, but if `name` is `"loc accent_tilde"`, then line 218 adds a `FLAG_LOCALIZED` flag to the object created in line 270 and returns this new object. 

According to **KeyValue.equals**, the objects returned in lines 213 and 218 representing the same symbol are distinct due to the difference in flags.  However, these two objects are compared in line 167 of Config.java. https://github.com/Julow/Unexpected-Keyboard/blob/402bf4990e33211ef47e794a095721080df18333/srcs/juloo.keyboard2/Config.java#L167-L169

Here, `extra_keys` are **KeyValue** objects created from method.xml, so they don't have the `FLAG_LOCALIZED` flag.  On the other hand, `key` is a **KeyValue** created from qwerty.xml, so it will have the flag if it's a localized key.  Therefore, `extra_keys.contains(key)`  will be `false` for any localized `key`, meaning that the extra keys are assumed to not be defined in the layout and are placed in the second row by default.

**Comment by Julow** [comment]
I noticed this too and it's very annoying, it seems to be introduced in 31d6a70.

Your debugging is right, thanks.

This can be fixed by specially handling the problematic flag in `Config.modify_layout` or in `KeyValue.equals` but this is not ideal because it adds complexity on something that didn't make much sense in the beginning.
My idea for now would be to handle the `loc ` prefix differently: remove the flag and remember the localized keys in a list in `KeyboardData`.

**Comment by kidhanis** [comment]
You could add a second `KeyValue` constructor with an extra `boolean` parameter. That way you don't need a list, but it will still create new objects for localized keys.

**Comment by Julow** [comment]
Fixed in ab987c7.

Adding anything to the `KeyValue` class wouldn't work as I don't wish to implement an `equals` function that don't compares every fields. I didn't use the list idea either, I instead added a layer in `KeyboardData` to store this kind of information (annotating individual keys but not turning them into different keys).
