### ISSUE TITLE
ALT key not working on Midnight Commander

### ISSUE THREAD

**Issue by GUUser91** [Julow/Unexpected-Keyboard#169]
I tried to used the ALT + ? command to execute a search option on Midnight Commander. It doesn't work. But if I use the ALT key from termux's built-in keys, It works.

Edit: Sorry had to re upload the video.

https://user-images.githubusercontent.com/77461922/175828752-60fc5962-4f06-4884-9b11-3a9b9c84eee3.mp4

**Comment by nanno** [comment]
Sorry for offtop
@GUUser91 as a workaround you may use Esc instead of Alt.
But with default MC configuration you want to be quick to use Esc+? - defaults set a 1 second timeout after which Esc is being rejected.
Go to Options -> Configuration and under "Esc key mode" untick "Single press" (disable timeout) or increase number to something like 5000000 (microseconds) for 5sec timeout. Just play around with different values and find what fits for you.
Esc should work in any other app as well, tested with Emacs.

**Comment by Julow** [comment]
I believe this is a bug in Termux. Please re-open if you think the opposite.

**Comment by Julow** [comment]
Sorry for dismissing the issue so fast. I believe this should be fixed in c5f2c0b, which will be released.
