### ISSUE TITLE
Home key doesn't work

### ISSUE THREAD

**Issue by sdrapha** [Julow/Unexpected-Keyboard#17]
The Home key ( fn + left arrow ) doesn't work in all 3 different devices I use this keyboard.

**Comment by Julow** [comment]
Thanks for the report ! The home key is indeed totally wrong. It was sending the actual home key (for opening the application launcher, which has no effect when sent from a virtual keyboard) instead of the "home movement" key (the one we want).

This is fixed for the next release (3e332dbf54ca51b6d63f3ae01a244d0e4751fd42).

**Comment by sdrapha** [comment]
Awesome, thanks!
