### ISSUE TITLE
Support typing by swipe/glide

### ISSUE THREAD

**Issue by sloanlance** [Julow/Unexpected-Keyboard#205]
Please add support for typing by sliding one's finger over the letters of words, rather than precisely tapping each individual letter. Some other keyboards refer to that typing style as "swipe to type" (Samsung keyboard)  or "glide typing" (Gboard).

Ideally, it should work in Termux, too, WITHOUT activating the text input mode.

**Comment by Julow** [comment]
Sorry, this is not something that I plan to implement. It seems like a huge amount of work that I can't spare and it's generally not a feature that I would use or understand well.

Of course, if someone is interested in coming up with a prototype, I won't oppose merging it. Please re-open this issue if anyone is interested in doing the work.

**Comment by Lloyd-Jackman-UKPL** [comment]
@Julow would you consider removing the below from the keyboard description or otherwise rephrasing as this led me to believe it had such functionality

**Comment by sdrapha** [comment]
Just my 2 cents, as an user, I'm no maintainer of this keyboard. But the use of the `Swipe` word is technically correct for this keyboard.
https://www.merriam-webster.com/dictionary/swipe

I guess what you were looking for was "connecting keys without lifting the finger" which is not the true meaning of the swipe word. But trully, there is some name appropriation regarding that because of the swift keyboard used the tern and got so popular.

Just a healthy discussion, I don't actually care if the maintainer decides to change it or not. all good to me anyway.

**Comment by Lloyd-Jackman-UKPL** [comment]
Hello @sdrapha that's a fair point and I respect your comment.  I guess the keyboard Swype has popularised this form of input and suspect it may lead to confusion in others as it did with me.  Please don't take this as criticism as the keyboard produced is a great product, just not the one I was looking for as this input form is important for me.

**Comment by Julow** [comment]
Thanks for the comment. I tried using "short swipe" and "pulling" but went back to "swipe" because it fits better in a shorter sentence: (73ef7c6)

> The main feature is easy typing of more characters by swiping the keys toward the corners.

What do you think ?

**Comment by Lloyd-Jackman-UKPL** [comment]
I think that would work great and reduce the potential for confusion.

Again, while this wasn't the keyboard I was looking for, its a great product with some original features being built in the right way. I wish you luck with the project!

Lloyd

Sent from ProtonMail mobile

-------- Original Message --------
