### ISSUE TITLE
Resize feature?

### ISSUE THREAD

**Issue by nolefty** [Julow/Unexpected-Keyboard#21]
Is a feature coming that will enable resizing of the  keyboard? It's gigantic.

**Comment by Julow** [comment]
There's a "Key height" option in the settings that will change the vertical size of the keyboard.

**Comment by nolefty** [comment]
actually, the app can't be found anywhere on my device. I noticed someone
else you the Play Store reviews mentioning the same problem.

**Comment by Julow** [comment]
That might be because you need to enable the keyboard in the system settings. Keyboards are not enabled as soon as they are installed for security reasons.

System Settings > System (near the bottom) > Languages & Input > Virtual keyboard > Manage keyboards.

You are right that it's hard to guess that and that a lot of people have the same problem. This can be fixed by adding an application icon that shows some explanations. This is not planned for the next release but the release after it.

**Comment by Julow** [comment]
Did the app work for you ? I'm closing the issue for now, please re-open at any time!
