### ISSUE TITLE
bug shift

### ISSUE THREAD

**Issue by xi7** [Julow/Unexpected-Keyboard#241]
https://user-images.githubusercontent.com/67331785/201440677-12382042-9a30-44f3-910a-ee5a63bf5368.mp4

when shift enabled cant use delete

**Comment by Julow** [comment]
It seems that the application you use don't recognize the delete key whether shift is enabled. 
This can be considered a bug in the app but perhaps the keyboard should take care of some editing actions whenever the app don't. Related: https://github.com/Julow/Unexpected-Keyboard/issues/101 https://github.com/Julow/Unexpected-Keyboard/issues/233

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/201488717-9d255247-bfbf-4dc4-ac38-fb38519db4c3.mp4

never work here

**Comment by Julow** [comment]
Thanks for the clarification!

**Comment by DeMoN100** [comment]
> recording_20221112_151133.mp4 
> never work here

It must be device specific because I do not experience this issue. It would probably help if you listed your devices specifications.

https://user-images.githubusercontent.com/8564572/201507396-15d1fe5c-c63e-4be4-b07f-f48b438b5211.mp4

**Comment by xi7** [comment]
i use android 5.1

**Comment by Julow** [comment]
My idea stands. Different versions of Android and different applications don't behave the same and sometimes in clearly broken ways (for example, FluffyChat crashes when Ctrl or Shift is on, https://github.com/Julow/Unexpected-Keyboard/issues/99).

Currently, the keyboard only types characters or sends key events. The idea would be to also take care of some editing actions (eg. copy, paste, selection, delete a word, etc...) instead of sending the key events directly (eg. Ctrl+C, Ctrl+V, etc...).
It's unclear how to detect whether this editing mode should be enabled. For example, it should be enabled in FluffyChat and disabled in Termux but what about the text editors/notes applications ?

If anyone has time to work on this, contribution welcome :)

**Comment by Julow** [comment]
I've opened an issue to keep track of this problem: https://github.com/Julow/Unexpected-Keyboard/issues/242
I'll close related issues to keep the ideas clear.
