### ISSUE TITLE
[Feature Request] Adjust Margins and Height of Landscape Keyboard and Vertical Keyboards Separately

### ISSUE THREAD

**Issue by ARGENTI21** [Julow/Unexpected-Keyboard#270]
Really thankful to be able to modify the margins and size of the keyboard, but it would be much more convenient if we could adjust the settings separately for landscape keyboard and  vertical keyboard.

Maybe best if all keyboard settings were adjustable for landscape and vertical keyboards separately.

-Issue:
Currently have "Margin Bottom" set to "50dp" which positions the vertical keyboard perfectly, but when switched to landscape keyboard, it puts the keyboard too high and leaves the viewing window above the keyboard to small to see.
Wish I could leave the vertical keyboard "Margin Bottom" at "50dp" and landscape keyboard "Margin Bottom" at "0dp"

**Comment by sdrapha** [comment]
I don't want to derail the OP request, but it's kind of related, I always wanted to have left margin separate from right margin, instead of just symetric horizontal margins.
That way I could tune my keyboard settings to better suit one-hand operation.
I had plans to implement that in my fork, but I'm not having any time free at all to give it a shot. So I'm just sharing the idea, if it gets some traction togethers with OP request.

**Comment by Julow** [comment]
Thanks for the report. I duplicated the margin options for landscape and portrait: fd0f0d5, a199962.

@sdrapha I don't think an asymmetric margin would help typing with one hand, as it would only make smaller keys. A different layout is needed. I have some ideas but no time for experimenting at the moment (26 letters would easily fit on 3x3 bigger keys left or right aligned, the other symbols/digits would be on a separate screen).
Please open an other issue if you have more ideas about this.

**Comment by sdrapha** [comment]
@Julow 
To illustrate better my idea, I will explain my use case:
My phone has a 5.5" screen, I always use it in portrait mode. and when one-handed operated, my thumb reaches 90% of the screen laterally. If I could increase the margin a bit, I would reach 100% of the keys. But currently, the symmetrical margin setting also shrinks the keyboard on the side I don't need, also making the keys even smaller yet.
So that is why I wanted assymetrical margins.

If you had a tablet in mind, I agree that just the margins alone doesn't fix the issue, because it's too much. but, on my scenario, it does make sense.

**Comment by Julow** [comment]
@sdrapha You can add a `shift` to every rows of your layout to test this. I would like to hear your experience.

**Comment by sdrapha** [comment]
@Julow , good idea, I'll test a modified layout for a while to make sure of the concept

**Comment by sdrapha** [comment]
@Julow I've done the modified layout in my fork https://github.com/sdrapha/Unexpected-Keyboard , if you are curious to test it yourself.
there should be debug apks, inlcuding one called fork_debug which has a different namespace than yours, so you can install it in paralell to your own debugs versions.
I just made it, so I need time using it now to gather my own conclusions about it, but initial testing seems promising.

**Comment by Julow** [comment]
Interesting, thanks.
