### ISSUE TITLE
[Feature Request] Optional Ability to Add Additional Layer of Number Buttons at Top of Keyboard Like Traditional Android Keyboards Have

### ISSUE THREAD

**Issue by ARGENTI21** [Julow/Unexpected-Keyboard#272]
An option that could be available in settings.
For convenience of quickly typing in numbers without having to press and swipe every single number.

**Comment by joeyeti** [comment]
Seconded!

**Comment by sdrapha** [comment]
Agreed!, I do use my keyboard like that, on my fork, which I implemented in a custom layout. It would be nice to have that feature baked in for everyone.
One observation I can make about that: since I've been down that road, once you get to the point of having an extra row on the top, you end up with duplicate symbols, from the original layouts keys. if you just remove those duplicate keys, you end up with premium space just empty, those are prime locations for extra keys. So it worth editing the whole layout, to make it more efficient, instead of just adding a setting to show or hide the number extra row. That was my personal conclusion.
So now I have a qwerty layout with numbers, and one without it. And I can choose which one I want to use in the settings. That is a simple method that doesn't require a whole lot of code refactoring.

**Comment by Julow** [comment]
This is a commonly requested feature that I plan on implementing.

@sdrapha The digits would be removed from their current position when the number row is visible, leaving room for extra keys. Perhaps editing keys could be added there too ?

**Comment by sdrapha** [comment]
@Julow 
I currently use two custom layouts:
![Screenshot_20230115_191942](https://user-images.githubusercontent.com/25059996/212575490-47fc44ea-edc2-4894-a97b-5f5495cc4227.jpg)

and this one:
![Screenshot_20230115_191913](https://user-images.githubusercontent.com/25059996/212575500-94ea284e-ec18-4d63-bd22-521350660335.jpg)


Since the number keys were taken out of their original place, I had extra room to redistribute all the extra keys. I had the goal to have just one extra key on the upper part, and one on the bottom, in general it's easier to swipe and error proof, no matter the swipe direction.
I redistributed the extra keys to be similar to an actual keyboard. so their position keeps the relationship closer to a physical kbd.

I choose to leave the number row shorter in height, with no extra keys. that was the best compromise on my tests to have accurate typing with no errors, or cluttered looks.

the addition of the new editing keys would indeed be very nice, I like the idea. I currently don't have those keys available, as my custom layout was made on top of version 16. I have plans to rebase my modifications on top of the latest build, just didn't have time yet.

obs: my second screenshot, where I have the extra 'editing' row on top, I will put the new editing keys there as needed.

obs2: if you programatically remove the digits and replace them with editing keys, that works. It's just a lost opportunity to have an optimal layout (position of extra keys). but I guess that also makes it easier to maintain, since it happens automatically, on every layout, I agree with that. In the end, I will always end up with my personal layout custom made anyway, so I'm not too worried. Unless the programmatic method breaks a layout that have the numbers on `key0`.

**Comment by Julow** [comment]
I've added the optional number row in 540384b. I'd appreciate if you could try it and report feedback: https://github.com/Julow/Unexpected-Keyboard/actions/runs/4048929888

The numbers are removed from the main layout while the number row is visible, but other keys are not redistributed. The empty spaces are not so bad to me.

**Comment by Julow** [comment]
This is released.
