### ISSUE TITLE
Few Suggestion from iyr

### ISSUE THREAD

**Issue by Raja-Katadi** [Julow/Unexpected-Keyboard#372]
`Redo` and `undo` mostly working but sometimes not getting right.

> When selecting a text and pressing capslock must make the selected text to caps.

`s.all,copy,paste` these are excellently working and these are what i asked in past.

If you create a text editor it would be very useful for android devices...Specially Keybinding like vim..."Unexpected keyboard+unexcepted text `editor"[😅] would be op

Hope you liked my suggestions,Thanks for creating this for all of us...iyr

**Comment by Julow** [comment]
The undo/redo problem is well known and is not due to the keyboard. It's possible to overcome this problem in the keyboard itself with a lot of work: https://github.com/Julow/Unexpected-Keyboard/issues/242

Capitalizing selected text would be one of the first functions of such an "editing mode". I wrote both of these in the other issue to not forget.

I do not plan to implement a text-editor. I'd suggest using Vim inside Termux.

Thanks for the suggestions! I'll close this issue, don't hesitate to open more for other suggestions.
