### ISSUE TITLE
Custom layout feature requires unescaped characters

### ISSUE THREAD

**Issue by frimdo** [Julow/Unexpected-Keyboard#381]
While layouts in `res/xml/` requires escaped characters (for example ``` key0="\\" ``` instead of ``` key0="\" ``` for character ``` \ ```), the custom layout feature does not need escaping. 

To try this, just use this layout using custom layout feature.
```xml
<?xml version="1.0" encoding="utf-8"?>
<keyboard>
  <row>
    <key key0="\\"/>
  </row>
</keyboard>
```

Expected result: Keyboard with single key with character  ``` \ ```.
Observed result: Keyboard with single key with character  ``` \\ ```.

**Comment by frimdo** [comment]
The same result is to be seen using [unexpected-keyboard-layout-editor.lixquid.com](https://unexpected-keyboard-layout-editor.lixquid.com/]

**Comment by Spike-from-NH** [comment]
That's peculiar; my custom QWERTY doesn't escape backslash either. I assumed it's because it's XML, and a good XML parser sees the quotation marks and correctly refuses to give the contents special processing. But my file does use & notation to specify the characters < and >. 

The inconsistent treatment should be solved.

**Comment by Julow** [comment]
Some characters have special meaning when the XML file is placed in the `res/` directory: `? @ # \`. They don't have this special meaning when passed to the "custom layout" option, which doesn't have a concept of escaping with `\`.

I suggest sticking with `\? \@ \# \\` to avoid surprises when eventually adding layouts into the app. The app will adapt: e025fdd.
