### ISSUE TITLE
Tab keys 1.11.x

### ISSUE THREAD

**Issue by rudolfmu** [Julow/Unexpected-Keyboard#39]
The Tab key doesn't work on 1.11 up.

Tested on OI Notepad and
https://f-droid.org/packages/bander.notepad/

**Comment by sdrapha** [comment]
My 2 cents here, just as an happy user of this keyboard and subscribed to the repo.
Isn't this referenced app 10 years old, made for android 1.5 ? I would say the issue is on the notepad side, not correctly dealing with the special key TAB, but I guess even the source code for the notepad app is gone to look at.
I'm taking time to put my 2 cents here, because I also paid close attention to the TAB behavior, and this app is doing it right. I test it a lot. You can test/compare your issue by connecting a physical(bluetooth) keyboard to your phone and test it. that should be the benchmark behaviour, and that is what this keyboard does.

**Comment by rudolfmu** [comment]
With version 1.10 tab works. With 1.11.x it does not work. Clear?

**Comment by Julow** [comment]
I think what @sdrapha is saying is that the problem might be on the application's side. The behavior of the tab key did change between 1.10 and 1.11 but I believe the new behavior is generally more correct. (related issue: https://github.com/Julow/Unexpected-Keyboard/issues/18)

I don't have a bluetooth keyboard or a usb hub at the moment but I expect it will behave the same.

What the old Tab key did was to literally write the Tab character in the text box. The new behavior is to send the dedicated "key code" for the Tab key, this is what most editors expect and what most keyboards do.
I just added a key combination (7af579a): `Fn+Tab` will now send the tab character.

I didn't find a way to detect how the application would react to the tab "key code" vs the tab character, so I can't fix your issue yet. If you have an idea, contribution welcome.

**Comment by Julow** [comment]
Btw, thanks @sdrapha for suggesting the `Fn+Tab` combination.
