### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by cachewram** [Julow/Unexpected-Keyboard#471]
Hello @Julow 

What do repl and auto do? Replit??

How do I annotate my entries with labels like layout request or enhancement request, bug etc?

I saw someone request a user manual for the unexpected keyboard. Could the wiki section be used to create one? :o[)
Cachewram

**Comment by Julow** [comment]
> What do repl and auto do?

Nothing! These keys exist in Android but do nothing. They will be removed in the next release.

> How do I annotate my entries with labels

There's labels on Github. Can you edit them on your own issue?

> Could the wiki section be used to create one?

That's a solution but I was also thinking of a collection of `.md` files in the repo, so that it can be translated and eventually embedded in the app.
The biggest problem is finding time to write the content though.

**Comment by cachewram** [comment]
Nothing. Thats 30 minutes of my life I can see swirling down a drain hole then! Great. And are there any more of these delightful suprise sleeper keys I can replace or repl  with ones that actually do something when you press them there at all? :o[]

**Comment by Julow** [comment]
I'll close this issue, feel free to open a new one for more questions.
