### ISSUE TITLE
How to use keyboard 

### ISSUE THREAD

**Issue by nikosbo** [Julow/Unexpected-Keyboard#475]
Dear all,
I don't understand how to use keyboard: how to activate swipe, how to insert special characters , numbers and other second chars in every button.
Could you help?

**Comment by Spike-from-NH** [comment]
I can explain swipe. Instead of tapping a key, press the middle of a key and before lifting up, drag your finger toward the corner that has the desired legend.

Pressing the 123+ key at the lower left changes the entire keyboard, and pressing ABC on the other keyboard changes it back. If you spend some time experimenting, it will answer your questions, or at least inspire some more specific questions.

**Comment by nikosbo** [comment]
Ok, found how to do.
Swipe is not available to write words, do you confirm?

Nikos

Il 5 ottobre 2023 02:49:46 CEST, Spike ***@***.***> ha scritto:

**Comment by Spike-from-NH** [comment]
You can make a keystroke or a swipe produce an entire word. See my #345. Since that conversation, I've edited my own qwerty.xml further; I can now swipe to get "you" and "the ".
![20231005_092845](https://github.com/Julow/Unexpected-Keyboard/assets/126838489/50bf457d-ce0a-43d0-b8b3-2088fd26e53b)

**Comment by Julow** [comment]
Swipe typing is indeed not supported by the app. Discussion about it continue here: https://github.com/Julow/Unexpected-Keyboard/issues/484

I'm closing this issue, feel free to open a new one for new questions.
