### ISSUE TITLE
how do you simply type a number using this thing ???

### ISSUE THREAD

**Issue by consorts** [Julow/Unexpected-Keyboard#511]
this is insane  ¯\\_(ツ)_/¯  
no matter what i press or how i swipe,   
https://imgur.com/Lj5YuPk
i can't get any numbers to show up.  

_i have no idea how you get to the smilies  
or to the app setup gear on the Fn square.  
there no instructions anywhere how to use this,  
and the readme file has nothing instructional._

v1.24.0 from playstore on a android 12 smartphone

**Comment by Spike-from-NH** [comment]
In the installation setup (QWERTY), the numerals are on the top row. Instead of pressing the key, put your finger in the center of the key and SWIPE in the direction of the numeral.

On the Fn key, there is a "gear" logo. Swipe this to go to the Settings page. One setting is "Show number row". This is what you want.

**Comment by Julow** [comment]
Version 1.25.0 now ships a short video that explains this. You can see it on the [README](https://github.com/Julow/Unexpected-Keyboard/blob/master/README.md).
