### ISSUE TITLE
Unintuitive arrow key

### ISSUE THREAD

**Issue by MaxGyver83** [Julow/Unexpected-Keyboard#56]
Thanks for this awesome app! I really like the concept of swiping to the key corners for accessing additional keys!

Except for the arrow key:

![Arrow key](https://user-images.githubusercontent.com/13970628/152232543-2a912032-09e5-4c28-bb35-1e9475cf9d56.png)

It's not intuitive at all swiping diagonally if you mean left, right, up or down. It would make more sense this way:

![Arrow key edges](https://user-images.githubusercontent.com/13970628/152232629-5d0d63c5-7013-4677-bcee-9baf224af361.png)

I have already implemented this. Just wait some minutes for my pull request.

**Comment by avently** [comment]
disagree here. i figured out how to use the keyboard even without reading the docs and the first thing i did is swiped on the arrow keys. so it's intuitive, cool and consistent with other keys

**Comment by sdrapha** [comment]
The old arrows worked fine for me also, @avently. BUT the HOME, END, PG UP and PG DOWN, were always confusing. I merged @MaxGyver83 changes to my fork and I'm currently using it. The Home/END/PGUP/DOWN works better now.  For the regular arrow keys, I keep going diagonally because of muscle memory, but I want to like this new layout, make sense to me even if it's not consistent with the other keys. 
Well, I'm not concluding anything, I just need to test it for a little while longer.

**Comment by Julow** [comment]
Merged :)
