### ISSUE TITLE
layout the spacebar row keys?

### ISSUE THREAD

**Issue by TaokyleYT** [Julow/Unexpected-Keyboard#620]
in the custom layout file it seems that the row including ctrl and spacebar cannot be customized. I have tried to make a row in the custom file with spacebar stuff thinking it can override the original row, resulted in 2 identical rows at the bottom and all other keys compressed onto the left side of the screen.
Is there ways to customize the bottom row?

**Comment by Spike-from-NH** [comment]
If you are defining your own bottom row, you must specify
  `<keyboard bottom_row="false"`...
to turn off the automatic one.

JapanYoshi is developing a reference page for the XML; see #614.

**Comment by Spike-from-NH** [comment]
The compression to the left side surely reflects an error in your XML. Is each `<row>` tag matched with a `</row>`?  If this problem persists after you follow my previous advice, please share your XML file; the error should be easy to spot.

**Comment by TaokyleYT** [comment]
just messed up the width value a bit, it there template for bottom row? (width value, height value) I can't find it anywhere

**Comment by Spike-from-NH** [comment]
@JapanYoshi, do you know? If so, please include it, as well as where to find QWERTY, in your documentation.

It wouldn't be hard to write a `<row>` that produces the current bottom line. The space bar has `slider="true"` so holding it down and moving your finger to the left or right produces precise cursor movement.

However, Julow has recommended that users stay with the built-in bottom row in order to pick up any future enhancements.

**Comment by JapanYoshi** [comment]
No, I don’t know the formula for the default bottom row.

**Comment by Spike-from-NH** [comment]
@alotbsol555, it certainly looks like that's what this file is for.

**Comment by Julow** [comment]
Is this issue resolved ?
