### ISSUE TITLE
[feature] forcibly show the keyboard at any time

### ISSUE THREAD

**Issue by GUUser91** [Julow/Unexpected-Keyboard#69]
I want to open up the Unexpected-Keyboard app even if there is no text field in focus.

For example, the Hacker's Keyboard app has this feature. It has a notification option that if I tap, the keyboard will pop up. Here's a video of me opening the Hacker's Keyboard app to use the keyboard shortcuts on the mpv app.

https://user-images.githubusercontent.com/77461922/153512355-075112bf-dcc2-4dbf-bddf-68dfe484a88a.mp4

**Comment by 07416** [comment]
Was it ever possible to use Home/End and PG UP/DN keys in a web browser on Android? Do the Android browsers support hotkeys in the first place?

**Comment by Julow** [comment]
That's an interesting idea, thanks!

@07416 I think at least browser extensions will be able to interpret the key presses (eg. vimium). Other android interfaces have hotkeys (even though they are generally of bad quality).

**Comment by dilipkn007** [comment]
In addition to that make it floatable

**Comment by Efreak** [comment]
@07416 I regularly use a media remote with my tablet. The arrow keys are implemented as dpad buttons, and the page keys are just pgup/pgdn. This works perfectly in Firefox/Lynket as well as several text editors and other apps; with the ability to cast the screen, I'd very much expect standard keyboard navigation to work in any other browser as well.

The entire Android interface does have basic hotkey support (ctrl+zxcva works in any standard text field, alt+tab switches apps, arrow keys navigate lists and the home screen, etc), which is rather expected imo since Android *does not require a touchscreen*--while this isn't useful for personal devices, I've seen kiosks built on Android that use a button, trackball and keyboard, with a standard display behind heavy plastic. Much cheaper than replacing a touchscreen every time it gets vandalized.

**Comment by mysori** [comment]
this hackers keyboard feature is no longer working on Android 12 and the hackers Keyboard project is dead and the developer is not interested in updating it anymore, so it has become important that this feature gets implemented in unexpected Keyboard.
This feature is more useful for educational purposes than  gaming or entertainment purposes as there is no built support in Android to achieve this.

**Comment by Julow** [comment]
Unfortunately, the mechanism for doing that has been removed in Android 12 (the [SHOW_FORCED](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#SHOW_FORCED) flag has been deprecated and has changed meaning at the same time).

For users of Android 11 or below, this is still possible but I'd prefer not to invest time in it, as it won't be long until I have to explain why it doesn't work anymore after an upgrade.

I don't know if there's a different solution but couldn't find any yet, please re-open if that's the case.
