### ISSUE TITLE
Can the swipe delay be customized?

### ISSUE THREAD

**Issue by 07416** [Julow/Unexpected-Keyboard#70]
When typing any longer alphabetical string without focusing on the output, I tend to see as much as 25% accidentally added special characters. Is it possible to adjust the delay for swipe-detection? I feel that even 500ms ("swipe-and-hold") or close would be fine for my use (I rarely type on mobile and prefer reliability).

Worth noting that I use a low scaling setting in Android.

**Comment by Julow** [comment]
I'm closing this issue due to lack of feedback. Some issues related to low scaling might have been fixed since.
Also, a "swipe and hold" gesture is not how the keyboard is supposed to be used. I'm not against as I'm thinking of adding a "hold" mechanism to lock modifiers but more justifications are needed for the other keys.

**Comment by 07416** [comment]
For the record, I see vastly less mistyped characters now (but also gaining more experience with using the keyboard may have had an effect, mind you).
