### ISSUE TITLE
Neo Bone missing German characters

### ISSUE THREAD

**Issue by DerMBen** [Julow/Unexpected-Keyboard#741]
As the title says, the "latn_bone" layout doesn't feature dedicated keys for the "ä", "ö", "ü" letters necessary for writing in German, even though the original "bone" layout includes them. They can be typed using the diacritics, but for the implementation of a layout specifically designed for the german language, this is quite cumbersome. I understand this was probably done as a space saving measure, but the standard german layout accomodates for these characters too.

**Comment by raelite** [comment]
one thing u could try is > add keys to keyboard > ö (checked). now if u hit ö, some keys get the dots below 'em, just downloaded this keyboard and damn it is kinda cool but extremely hard to hit those keys properly sometimes…

**Comment by Julow** [comment]
The bone layout is quite large and it seems that the contributor who added it to the app tried to make it fit in the usual 10 columns. I agree it feels wrong that these keys are not on the keyboard, even as swipes.

You can experiment by copying the layout definition into a "Custom layout" in the app settings and changing it. The layout definition is here: https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/layouts/latn_bone.xml
I'll include your changes if you find them satisfactory :)

The bone layout was added in https://github.com/Julow/Unexpected-Keyboard/pull/155 by @quantenzitrone.
@quantenzitrone What do you think of this issue ?

**Comment by quantenzitrone** [comment]
I should probably make change bone to be more like the desktop version and use a custom layout with my space-saving measures. When I asked the neo people if they wanted to add Unexpected Keyboard to their wiki, they denied, because my implementation differs too much from the original.
I also noticed that I forgot to add `$`, but never got around to fix that.
I'll try to find the time to fix up the bone layout in the near future.

**Comment by Julow** [comment]
Thanks for maintaining the layout :)
