### ISSUE TITLE
[feature request] modify keyboard character (font) size

### ISSUE THREAD

**Issue by 58673** [Julow/Unexpected-Keyboard#744]
How to change the keyboard icon/character/symbol size? The defaults are hard to discern -- even with normal eyesight I can hardly see some characters in the corners.

**Comment by 58673** [comment]
> In the Settings (swipe the gear logo), in the Style section, try the setting "Label size". 

Great.

I suggest changing the default value.

**Comment by Spike-from-NH** [comment]
As shown, I agree the default is small. But changing the default requires me to change my 1.30x on all devices to retain my preference. No; please maintain backward-compatibility!

**Comment by Julow** [comment]
Both approach are good :) As you have made the change, could you open a PR ?

**Comment by bokidori** [comment]
I opened a PR with the mentioned first approach - just increasing the default label size which does not affect user set preferences. Upon testing it today much longer than I'd like, I don't believe it solves the issue of label size becoming too small when keyboard height is reduced.

Could @Spike-from-NH or @58673 please mention their keyboard height and label size values used? Did labels become too small because keyboard height was reduced from default 35%?

For me:
Device 1, label size 1.3, keyboard height 27%.
Device 2, label size 1.2, keyboard height 31%.

**Comment by Spike-from-NH** [comment]
Oh, I see—You don't want to change what 1.00x means, only what value comes up initially. Then my objection is wrong.

I have keyboard height Landscape(40%,4-row layout), Portrait(30%,5-row layout), Labels 1.30x.
