### ISSUE TITLE
feature request: edit keyboard layout

### ISSUE THREAD

**Issue by melsiir** [Julow/Unexpected-Keyboard#758]
this app seem unique in it typing style .
but i dont like to swipe everytime i want to write a charactor .
if i can customize my keyboard to add more raws of charactors to the keyboard thats will make very handy and convenient for programming typing.

He is app called codeboard using this idea
![Screenshot_٢٠٢٤٠٩١٩-٢٢١٢٥٧_Termux](https://github.com/user-attachments/assets/d7f84b9a-a5be-48ec-a8a0-00250f512565)

**Comment by Julow** [comment]
Hi, you might try making a custom layout from the app settings. Some information are written here: https://github.com/Julow/Unexpected-Keyboard/blob/master/doc/Custom-layouts.md
However, swiping is a fundamental part of this app and supporting layouts with no swiping is not a goal. For example, I would not add long press for selecting alternative characters.

**Comment by ego-lay-atman-bay** [comment]
Something I want to add. If you come to unexpected keyboard and try to make it something else, then it's better for you to just use another app. For example, swiping is the main feature in unexpected keyboard. Trying to remove that is like removing it's identity, and turning it into something it's not. If you don't like swiping, just use another app, like codeboard.

**Comment by melsiir** [comment]
I didn't meant to get the feature removed but maybe adding ability to creating multiple profiles I mean the swiping is beneficial when you texting but If you right code this will be a torture it will be more convenient just to press the button especially that the coding process imply to many keyboard shortcuts which even more harder to code with swiping

**Comment by ego-lay-atman-bay** [comment]
I would disagree a bit, I find the swiping easier to code with, especially with the parenthesis, and all the types of brackets being on the same buttons. It's super fast to just type `()`. Not to mention, there's only one key for both quote characters, single quotes, and double quotes both on the letter M. This kind of grouping similar characters together, just makes writing code a whole lot easier than looking for multiple buttons on a dozen keyboard rows, since you can have pretty much every useful key on 3 rows. Of course I also have my display scale set to be a little bigger than normal, so it would take up too much space if I had more than 4 rows.

**Comment by Spike-from-NH** [comment]
@melsiir, you can certainly adapt to swiping in time. If you are having trouble getting swipes to register, you can play with "Swiping distance" in the  Settings. The custom layout that Julow mentioned above will let you minimize swiping, but at the cost of using more screen space. I came here after using Hacker's Keyboard, and believe swipes are faster than HK's long-press method.

**Comment by Julow** [comment]
Thanks all for discussing this. I'll close this as it seems resolved.
