### ISSUE TITLE
Cannot change language from Canadian

### ISSUE THREAD

**Issue by AmbrosiaDevelopments** [Julow/Unexpected-Keyboard#802]
My phone language is set to English Australian, my existing keyboard was in English and then installing Unexpected Keyboard it defaults the keyboard language to English (Canada). The only way I can see to change anything is to change the layout to QWERTY (US) or QWERTY (UK) but that doesn't actually change the language in the keyboard. I want to be able to set the keyboard but the settings page shows no options for language, only layout, which is different.

**Comment by GitAlasGo** [comment]
> My phone language is set to English Australian, my existing keyboard was in English and then installing Unexpected Keyboard it defaults the keyboard language to English (Canada). The only way I can see to change anything is to change the layout to QWERTY (US) or QWERTY (UK) but that doesn't actually change the language in the keyboard. I want to be able to set the keyboard but the settings page shows no options for language, only layout, which is different.

If you have multiple languages in unexpected keyboard, you can switch the language to another by swiping up or swiping down the spacebar.

**Comment by Spike-from-NH** [comment]
@AmbrosiaDevelopments, Unexpected Keyboard senses keystrokes and generates codes. The layout varies by locale but the codes do not; British E is the same as American E. (But Russian E is a different code, and if you pick the Russian layout, you will get it.) So I don't understand what you want to happen.

@GitAlasGo, knowing how to switch layouts might not help as Ambrosia states that both are unacceptable.

**Comment by Julow** [comment]
Thanks for your issue, should be fixed with 9bf0a20.

@Spike-from-NH The keyboard has to pick a language to then choose a layout to show by default. The language is picks is often not right and is visible to the user, creating this issue. 
The languages that can show up in the keyboard picker dialog are listed in: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/method.xml
This system is not very useful as the list of supported languages is quite small. Android will pick a similar language that is in the list otherwise. I'm considering getting rid of this system eventually, as many other mainstream keyboards did.

@GitAlasGo Spacebar up and down switch between layouts, not languages.

**Comment by srikanban** [comment]
Same with English (Indian) on phone, kb defaults to English (Canada)

**Comment by Julow** [comment]
@srikanban Thanks for reporting. Should be fixed in b3d28a6
