### ISSUE TITLE
Request to add Rupee symbol (₹)

### ISSUE THREAD

**Issue by HARDY8118** [Julow/Unexpected-Keyboard#90]
Addition of a ₹ symbol will be much appreciated.

**Comment by ChiefMikeK** [comment]
Suggest to add several(most) of the currency symbols to the number keypad
* rupee
* japanese yen
* chinese yuan
* philipine peso
* euro €
* currency symbol
* £ pound

**Comment by HARDY8118** [comment]
I was using Google's GBoard previously and I found Rupee(**₹**), Yen(**¥**), Euro(**€**) and Cent(**¢**) symbols in it. So I guess these symbols are the most common ones.

However it might be based on my region.

Also I think **€** and **£** are already included in the keyboard if we set to show all *accents* in the settings.

**Comment by Julow** [comment]
I have added the currency symbols you both suggested under the Fn key (5f47beb).

The mechanisms I have hoped to implement to place these symbols directly on the keyboard isn't ready for the next release but isn't abandoned either.

**Comment by HARDY8118** [comment]
Hi, I saw the code changes you made in commit 5f47beb5b0decf92b7804726d93b6eb53e2ca816, which according to me also should have worked. However it is showing euro symbols (€) for both F3 and F4 keys. Can you tell if you know why it is showing the same symbol twice. Thanks,
![Screenshot](https://user-images.githubusercontent.com/31590289/161427821-df8a2ba6-68e2-4699-8ca6-35e4123316cf.jpg)

**Comment by Julow** [comment]
@HARDY8118 It seems that you don't have the latest development version of the app. If you downloaded the APK from the Github CI, beware that it is a separate application from Android's point of view and you need to enable it in the settings.

Otherwise, I plan to release soon. It will look like this:
![image](https://user-images.githubusercontent.com/2310568/161432655-9942073e-ba7d-4775-9851-46134b936025.png)

**Comment by HARDY8118** [comment]
I received the update from fdroid today. Thanks a lot, it works so well.
