### ISSUE TITLE
[Change suggestion] Tab on the main layout

### ISSUE THREAD

**Issue by lupo-on-github** [Julow/Unexpected-Keyboard#97]
I use Tab a lot in Termux.
It would be nice to have Tab somewhere on the main layout.
I would suggest to use the Backspace button or the Tab button.

**Comment by Julow** [comment]
The tab is on left of the second row, on the top-left corner. (Near the `a` on QWERTY)

**Comment by Julow** [comment]
The Tag key is on every layouts.

**Comment by SuspectTyrannosaurus** [comment]
Could this Issue be used to request that the tab key be its own separate button? I'm not sure if that's what @lupo-on-github was suggesting, but it would be quite helpful. I use tab a **lot** in the shell and in text editors. 

Currently on QWERTY (on my screen at least) it isn't just near "A", it shares a button with it, so swiping is required:

![Screenshot_20220412-213816~2](https://user-images.githubusercontent.com/73123943/163102246-e3a52e8b-8e74-44b9-a7f2-ac91048473e9.png)

Hacker's Keyboard squeezes it in on the bottom row between Alt and Spacebar in Portrait mode:

![Screenshot_20220412-213826~2](https://user-images.githubusercontent.com/73123943/163102711-d0e560e6-15fd-458f-ae25-c8eafe1de49f.png)

I don't know if that would be the best place for it on Unexpected Keyboard.

**Comment by Julow** [comment]
@SuspectTyrannosaurus swiping is supposed to be easy, otherwise very important keys like the numeric keyboard or punctuation marks would be a bigger concern than Tab.
Do you use Tab more often than all the other keys or could you be used to the key in your previous keyboard ? In this case, it could be more useful to re-learn to type Tab rather than to change the layout.

**Comment by SuspectTyrannosaurus** [comment]
@Julow Thanks for your response. I think tab is particularly noticable as annoying to swipe because of how often I need to use it multiple times in a row. I agree that within the context of this project it's more of a training/usage issue, though.

**Comment by Julow** [comment]
I'm not against adding such an option but it needs to be justified because it's new and very specific. I'd appreciate if you could try modifying the keyboard on your side and investigate various solutions.
If you don't want to have an entire dev environment just for that, the CI should build the app even on your fork.
